### ISSUE TITLE
NPE: coordinate Null Pointer Exception

### ISSUE THREAD

**Issue by gernotstarke** [gernotstarke/circulizr#65]
last connection to be drawn fails

**Comment by gernotstarke** [comment]
exception in thread "AWT-EventQueue-0" java.lang.AssertionError: cannot advance connectionNode pointer, as segment 3 has no free connectionNodes after 619. Expression: (nextFreeConnectionNode < connectionNode.size()). Values: nextFreeConnectionNode = 619
    at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:404)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:650)
    at org.cirqlizr.domain.Segment.advanceToNextAvailableConnectionNode(Segment.groovy:78)
    at org.cirqlizr.domain.Segment$advanceToNextAvailableConnectionNode$1.call(Unknown Source)
    at org.cirqlizr.ui.DrawingCanvas.drawConnectionForNumberPair(DrawingCanvas.groovy:185)
    at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
    at groovy.la
